driver:
  name: ec2
  region: eu-central-1
  instance_type: m3.medium
  associate_public_ip: true
  security_group_ids: ["travis-ci"]
  interface: dns
  tags:
    Name: kitchen-test-inspec

transport:
  username: ec2-user
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_solo

verifier:
  name: inspec
  sudo: true

platforms:
  - name: windows-2008
    driver:
      image_id: ami-58918e34
    transport:
      username: administrator
  - name: windows-2012
    driver:
      image_id: ami-44918e28
    transport:
      username: administrator
  - name: windows-2012r2
    driver:
      image_id: ami-8a918ee6
    transport:
      username: administrator
  - name: suse-11sp3
    driver:
      image_id: ami-fc0033e1
  - name: suse-12
    driver:
      image_id: ami-a22610bf
  - name: redhat-65
    driver:
      image_id: ami-008ebf1d
  - name: redhat-71
    driver:
      image_id: ami-dafdcfc7
  - name: ubuntu-1204
    driver:
      image_id: ami-24232f39
    transport:
      username: ubuntu
  - name: ubuntu-1404
    driver:
      image_id: ami-48272b55
    transport:
      username: ubuntu
  - name: ubuntu-1510
    driver:
      image_id: ami-1b4a5977
    transport:
      username: ubuntu
  - name: fedora-22
    driver:
      image_id: ami-a88eb0b5
    transport:
      username: fedora
  - name: debian-8
    driver:
      image_id: ami-b092aaad
    transport:
      username: admin
  - name: centos-7
    driver:
      image_id: ami-e68f82fb
    transport:
      username: centos
  - name: aws-linux
    driver:
      image_id: ami-daaeaec7

suites:
  - name: default
    run_list:
      - recipe[os_prepare]
    attributes:
