---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7.1
  - name: centos-6.7
  - name: centos-6.7-i386
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: debian-6.0.10
  - name: debian-6.0.10-i386
  - name: debian-7.8
  - name: debian-7.8-i386
  - name: debian-8.1
  - name: debian-8.1-i386
  - name: fedora-21
  - name: fedora-21-i386
  - name: fedora-22
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: opensuse-13.2-x86_64
  - name: opensuse-13.2-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: ubuntu-12.04
  - name: ubuntu-12.04-i386
  - name: ubuntu-10.04
  - name: ubuntu-10.04-i386
  - name: mint-17.2-cinnamon
    driver_config:
      box: artem-sidorenko/mint-17.2-cinnamon

suites:
  - name: default
    run_list:
      - recipe[os_prepare]
    attributes:
